services:
  - type: web
    name: voice-vote-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
